map global normal n h
map global normal N H
map global normal e j
map global normal E J
map global normal i k
map global normal I K
map global normal o l
map global normal O L
map global normal h o
map global normal H O
map global normal <a-h> <a-o>
map global normal <a-H> <a-O>
map global normal j n
map global normal J N
map global normal l e
map global normal L E
map global normal k i
map global normal K I

map global goto o l -docstring 'line end'
map global goto n i -docstring 'line start'
map global goto i g -docstring 'buffer top'
unmap global goto l
unmap global goto g

map global prompt <c-n> <c-h>
map global prompt <c-e> <c-k>
map global prompt <a-l> <a-e>
map global prompt <a-L> <a-E>
map global prompt <c-l> <c-e>

map global view n h -docstring 'scroll left'
map global view e j -docstring 'scroll down'
map global view i k -docstring 'scroll up'
map global view o l -docstring 'scroll right'
unmap global view h
unmap global view j
unmap global view k
unmap global view l

map global insert <a-ret> <esc>
map global insert <s-ret> <esc>

colorscheme kanagawa
set-option -add global ui_options terminal_assistant=none

set-option -add global tabstop 2
set-option -add global indentwidth 2

add-highlighter global/ number-lines -relative

eval %sh{kak-lsp --kakoune -s $kak_session}

unmap global insert <tab>
map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <c-n> '<a-;>: try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object e '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object k '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://github.com/jdugan6240/kak-bundle

bundle smarttab.kak https://github.com/andreyorst/smarttab.kak
bundle kakoune-phantom-selection https://github.com/occivink/kakoune-phantom-selection
bundle kakoune-surround https://github.com/h-youhei/kakoune-surround

map global normal f ": phantom-selection-add-selection<ret>" -docstring "add phantom"
map global normal F ": phantom-selection-select-all; phantom-selection-clear<ret>" -docstring "enter phantoms"
map global normal <a-f> ": phantom-selection-iterate-next<ret>" -docstring "next phantom"
map global normal <a-F> ": phantom-selection-iterate-prev<ret>" -docstring "prev phantom"
map global insert <a-f> "<esc>: phantom-selection-iterate-next<ret>k"
map global insert <a-F> "<esc>: phantom-selection-iterate-prev<ret>k"

map global user y "$cat | wl-copy<ret>"

declare-user-mode surround
map global surround s ": surround<ret>" -docstring "surround"
map global surround r ": change-surround<ret>" -docstring "replace"
map global surround d ": delete-surround<ret>" -docstring "delete"
map global surround t ": select-surrounding-tag<ret>" -docstring "select"
map global normal <a-s> ": enter-user-mode surround<ret>"

hook global BufCreate .*\.latex %{set-option buffer filetype latex}
hook global BufCreate .*\.(vert|frag) %{set-option buffer filetype glsl}
hook global BufCreate .*\.wgsl %{set-option buffer filetype wgsl}
hook global BufCreate .*\.md %{set-option buffer filetype markdown}
hook global BufCreate .*\.e %{set-option buffer filetype ase100}

hook global WinSetOption filetype=(rust|c|cpp|haskell|python|java|glsl|wgsl) %{lsp-enable-window}

hook global WinSetOption filetype=.* %{expandtab;set-option buffer indentwidth 2}
hook global WinSetOption filetype=(Makefile|asm) %{
    noexpandtab
    set-option buffer indentwidth 0
}

hook global WinSetOption filetype=rust %{
    expandtab;
    hook window BufWritePre .* lsp-formatting-sync
    hook window -group rust-inlay-hints BufWritePost .* rust-analyzer-inlay-hints
    hook -once -always window WinSetOption filetype=.* %{
      remove-hooks window rust-inlay-hints
    }
}

hook global WinSetOption filetype=markdown %{
  add-highlighter window wrap

  hook -once -always window WinSetOption filetype=.* %{
    remove-highlighter window wrap
  }
}

provide-module ase100syntax %&
  add-highlighter shared/ase100 regions
  add-highlighter shared/ase100/ region "//" '\n' fill comment
  add-highlighter shared/ase100/string region '"' '"' group
  add-highlighter shared/ase100/string/ fill string
  add-highlighter shared/ase100/string/ \
    regex (\\[\\abefhnrtv\n])|(\\.) 1:keyword 2:Error
  add-highlighter shared/ase100/char region "'" "'" group
  add-highlighter shared/ase100/char/ fill string
  add-highlighter shared/ase100/other default-region group
  add-highlighter shared/ase100/other/ \
    regex ^\w[\w_\d]* 0:function
  add-highlighter shared/ase100/other/ \
    regex \W\K-?[0-9]+ 0:value
  add-highlighter shared/ase100/other/ \
    regex 0x[1-9a-f][0-9a-f]* 0:value
  add-highlighter shared/ase100/other/ \
    regex \b(halt|add|sub|mult|div|cp|cpdata|and|or|not|sl|sr|cpfa|cpta|be|bne|blt|call|ret)\b 0:keyword
  add-highlighter shared/ase100/other/ \
    regex (\x23\w+)[^\n]* 1:meta
&

hook global WinSetOption filetype=ase100 %{
  require-module ase100syntax

  add-highlighter window/ase100 ref ase100

  hook -once -always window WinSetOption filetype=.* %{
    remove-highlighter window ase100
  }
}

hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h|\n<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
        hook -once -always window InsertCompletionHide .* %{
            unmap window insert <tab> <c-n>
            unmap window insert <s-tab> <c-p>
        }
    }
}

hook global InsertChar \n %[ try %[
    execute-keys -draft <a-k>[})]<ret>
    execute-keys -draft kx <a-k>[{(]\h*$<ret>
    try %[
        execute-keys -draft kxs^\h*<ret> <a-k>\s+<ret> yjghP
    ]
    execute-keys -draft O
    execute-keys '<up>'
]]

hook global InsertChar \( %[ try %[execute-keys -draft hh<a-k>[^\\]<ret>; execute-keys )<left>] ]
hook global InsertChar \{ %[ try %[execute-keys -draft hh<a-k>[^\\]<ret>; execute-keys }<left>] ]
hook global InsertChar \[ %{ try %{execute-keys -draft hh<a-k>[^\\]<ret>; execute-keys ]<left>} }

hook global InsertChar \) %[ try %[execute-keys -draft <a-k>[)]<ret>; execute-keys <backspace><right>] ]
hook global InsertChar \} %[ try %[execute-keys -draft <a-k>[}]<ret>; execute-keys <backspace><right>] ]
hook global InsertChar \] %{ try %{execute-keys -draft <a-k>[\]]<ret>; execute-keys <backspace><right>} }
