"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = '[∙](bright-black) '
format = '$all$status$line_break$character'

[python]
symbol = "\ue73c "

[rust]
symbol = "\ue7a8 "

[dart]
symbol = "\ue798 "

[status]
disabled = false
