;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-confirm-and-exit-minibuffer
	kak-append-end
	kak-deselect-region
	kak-enter-insert
	kak-exit-insert
	kak-flip-region
	kak-goto-buffer-end
	kak-goto-end
	kak-goto-start
	kak-kill
	kak-next-char
	kak-next-line
	kak-next-word
	kak-prev-char
	kak-prev-char-extend
	kak-prev-line
	kak-prev-word
	kak-till-char
	keyboard-escape-quit
	multiple-cursors-mode
	))

(setq mc/cmds-to-run-once
      '(
	mc/mark-next-lines
	undefined
	))
