theme = "everforest_dark"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
k = "insert_mode"
K = "insert_at_line_start"
h = "open_below"
H = "open_above"
j = "search_next"
J = "search_prev"

[keys.select]
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"
k = "insert_mode"
K = "insert_at_line_start"
h = "open_below"
H = "open_above"
j = "search_next"
J = "search_prev"

