theme = "everforest_dark"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
O = "no_op"
k = "insert_mode"
K = "insert_at_line_start"
h = "open_below"
H = "open_above"
j = "search_next"
J = "search_prev"
C-n = "jump_view_left"
C-e = "jump_view_down"
C-i = "jump_view_up"
C-o = "jump_view_right"
"#" = "join_selections"
"A-#" = "join_selections_space"
I = "keep_selections"
A-I = "remove_selections"

[keys.normal.C-w]
j = { s = "hsplit_new", v = "vsplit_new" }
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
C-n = "jump_view_left"
C-e = "jump_view_down"
C-i = "jump_view_up"
C-o = "jump_view_right"
N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"
h = "wonly"

[keys.normal.g]
j = "goto_next_buffer"
n = "goto_first_nonwhitespace"
o = "goto_line_end"

[keys.normal.z]
e = "scroll_down"
i = "scroll_up"
E = "half_page_down"
I = "half_page_up"
A-e = "page_down"
A-I = "page_up"

[keys.select]
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"
k = "insert_mode"
K = "insert_at_line_start"
h = "open_below"
H = "open_above"
j = "search_next"
J = "search_prev"
G = "join_selections"
A-G = "join_selections_space"
I = "keep_selections"
A-I = "remove_selections"
